name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./time-ui

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        npm install
        npm build
      env:
        REACT_APP_API_URL_PROD: ${{ secrets.REACT_APP_API_URL_PROD }}
        REACT_APP_GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
